//Aauí se trabajará con todos los objetos de tipo película que se van a crear
//
//para pegar este json se usa la extensión "PASTE JSON AS CODE, fue pegado de la pagina siguiente
//https://developers.themoviedb.org/3/movies/get-now-playing"
//// Generated by https://quicktype.io


class Pelicula {
  String posterPath;
  bool adult;
  String overview;
  String releaseDate;
  List<int> genreIds;
  int id;
  String originalTitle;
  String originalLanguage;
  String title;
  String backdropPath;
  double popularity;
  int voteCount;
  bool video;
  double voteAverage;

  Pelicula({
    this.posterPath,
    this.adult,
    this.overview,
    this.releaseDate,
    this.genreIds,
    this.id,
    this.originalTitle,
    this.originalLanguage,
    this.title,
    this.backdropPath,
    this.popularity,
    this.voteCount,
    this.video,
    this.voteAverage,
  });

  Pelicula.fromJsonMap(Map<String, dynamic> json)
  {
//     posterPath
// adult
// overview
// releaseDate
// genreIds
// id
// originalTitle
// originalLanguage
// title
// backdropPath
// popularity
// voteCount
// video
// voteAverage
//   
}


}


